// <auto-generated />
namespace Muusikapood.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview5-19254-05")]
    public sealed partial class kvaliteedd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kvaliteedd));
        
        string IMigrationMetadata.Id
        {
            get { return "201906050744558_kvaliteedd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
